"""revert_assignment_user_id_to_int

Revision ID: 0e90db353fcc
Revises: 6de925505248
Create Date: 2026-03-24 15:23:43.521371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0e90db353fcc'
down_revision: Union[str, Sequence[str], None] = '6de925505248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'project_users', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.drop_column('projects', 'previous_status')
    op.add_column('user_team_link', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_team_link', 'id')
    op.add_column('projects', sa.Column('previous_status', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'project_users', type_='foreignkey')
    # ### end Alembic commands ###
