"""add_audit_tables_and_user_email

Revision ID: 5e52bba644e7
Revises: 99ca54d81b48
Create Date: 2026-03-24 13:09:11.591635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e52bba644e7'
down_revision: Union[str, Sequence[str], None] = '99ca54d81b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_users', sa.Column('user_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_users', 'user_email')
    # ### end Alembic commands ###
