"""Convert billing_model and project_type to String

Revision ID: 60b8b5752aba
Revises: 87633ef8672b
Create Date: 2026-05-06 12:17:22.960162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '60b8b5752aba'
down_revision: Union[str, Sequence[str], None] = '87633ef8672b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AuditFieldsMapping',
    sa.Column('ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('EntityName', sa.String(length=150), nullable=False),
    sa.Column('FieldName', sa.String(length=150), nullable=False),
    sa.Column('DisplayName', sa.String(length=150), nullable=True),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.Column('IsVisible', sa.Boolean(), nullable=True),
    sa.Column('OrderNo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('AuditLogs',
    sa.Column('ID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('TableName', sa.String(length=250), nullable=False),
    sa.Column('Action', sa.Integer(), nullable=False),
    sa.Column('PerformedBy', sa.Uuid(), nullable=False),
    sa.Column('PerformedOn', sa.DateTime(), nullable=False),
    sa.Column('RecordName', sa.String(length=500), nullable=True),
    sa.Column('TransactionId', sa.Uuid(), nullable=False),
    sa.Column('Comments', sa.Text(), nullable=True),
    sa.Column('ModuleName', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('AuditMetaDataInfo',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('File_name', sa.String(length=255), nullable=True),
    sa.Column('StartDate', sa.DateTime(), nullable=False),
    sa.Column('EndDate', sa.DateTime(), nullable=False),
    sa.Column('ModuleOrEntityName', sa.String(length=255), nullable=True),
    sa.Column('CreatedOn', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('AuditLogDetails',
    sa.Column('Id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('AuditLogId', sa.BigInteger(), nullable=False),
    sa.Column('FieldName', sa.String(length=250), nullable=False),
    sa.Column('OldValue', sa.Text(), nullable=True),
    sa.Column('NewValue', sa.Text(), nullable=True),
    sa.Column('ValueType', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['AuditLogId'], ['AuditLogs.ID'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_table('auditlogs')
    op.drop_table('auditmetadatainfo')
    op.drop_table('auditlogdetails')
    op.drop_table('auditfieldsmapping')
    op.drop_constraint(op.f('fk_issues_priority_id'), 'issues', type_='foreignkey')
    op.create_foreign_key(None, 'issues', 'master_lookups', ['priority_id'], ['id'])
    op.drop_constraint(op.f('fk_milestones_priority_id'), 'milestones', type_='foreignkey')
    op.drop_constraint(op.f('fk_milestones_status_id'), 'milestones', type_='foreignkey')
    op.create_foreign_key(None, 'milestones', 'master_lookups', ['priority_id'], ['id'])
    op.create_foreign_key(None, 'milestones', 'master_lookups', ['status_id'], ['id'])
    op.drop_constraint(op.f('fk_project_members_prev_inv_status_id'), 'project_members', type_='foreignkey')
    op.drop_constraint(op.f('fk_project_members_inv_status_id'), 'project_members', type_='foreignkey')
    op.create_foreign_key(None, 'project_members', 'master_lookups', ['previous_invitation_status_id'], ['id'])
    op.create_foreign_key(None, 'project_members', 'master_lookups', ['invitation_status_id'], ['id'])
    op.alter_column('projects', 'billing_model',
               existing_type=mysql.ENUM('TM', 'FIXED', 'MILESTONE'),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('projects', 'project_type',
               existing_type=mysql.ENUM('INTERNAL', 'EXTERNAL'),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_projects_project_name'), table_name='projects')
    op.create_index(op.f('ix_projects_project_name'), 'projects', ['project_name'], unique=True)
    op.drop_constraint(op.f('fk_projects_status_id'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('fk_projects_priority_id'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'master_lookups', ['status_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'master_lookups', ['priority_id'], ['id'])
    op.drop_constraint(op.f('task_lists_ibfk_1'), 'task_lists', type_='foreignkey')
    op.create_foreign_key(None, 'task_lists', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_timelogs_public_id'), 'timelogs', ['public_id'], unique=False)
    op.drop_constraint(op.f('fk_timelogs_approval_status_id'), 'timelogs', type_='foreignkey')
    op.drop_constraint(op.f('fk_timelogs_prev_approval_status_id'), 'timelogs', type_='foreignkey')
    op.create_foreign_key(None, 'timelogs', 'master_lookups', ['approval_status_id'], ['id'])
    op.create_foreign_key(None, 'timelogs', 'master_lookups', ['previous_approval_status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timelogs', type_='foreignkey')
    op.drop_constraint(None, 'timelogs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_timelogs_prev_approval_status_id'), 'timelogs', 'master_lookups', ['previous_approval_status_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_timelogs_approval_status_id'), 'timelogs', 'master_lookups', ['approval_status_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_timelogs_public_id'), table_name='timelogs')
    op.drop_constraint(None, 'task_lists', type_='foreignkey')
    op.create_foreign_key(op.f('task_lists_ibfk_1'), 'task_lists', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('fk_projects_priority_id'), 'projects', 'master_lookups', ['priority_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_projects_status_id'), 'projects', 'master_lookups', ['status_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_projects_project_name'), table_name='projects')
    op.create_index(op.f('ix_projects_project_name'), 'projects', ['project_name'], unique=False)
    op.alter_column('projects', 'project_type',
               existing_type=sa.String(length=100),
               type_=mysql.ENUM('INTERNAL', 'EXTERNAL'),
               existing_nullable=False)
    op.alter_column('projects', 'billing_model',
               existing_type=sa.String(length=100),
               type_=mysql.ENUM('TM', 'FIXED', 'MILESTONE'),
               existing_nullable=False)
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.create_foreign_key(op.f('fk_project_members_inv_status_id'), 'project_members', 'master_lookups', ['invitation_status_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_project_members_prev_inv_status_id'), 'project_members', 'master_lookups', ['previous_invitation_status_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'milestones', type_='foreignkey')
    op.drop_constraint(None, 'milestones', type_='foreignkey')
    op.create_foreign_key(op.f('fk_milestones_status_id'), 'milestones', 'master_lookups', ['status_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_milestones_priority_id'), 'milestones', 'master_lookups', ['priority_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.create_foreign_key(op.f('fk_issues_priority_id'), 'issues', 'master_lookups', ['priority_id'], ['id'], ondelete='SET NULL')
    op.create_table('auditfieldsmapping',
    sa.Column('ID', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('EntityName', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('FieldName', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('DisplayName', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('IsActive', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('IsVisible', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('OrderNo', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('auditlogdetails',
    sa.Column('Id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('AuditLogId', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('FieldName', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('OldValue', mysql.TEXT(), nullable=True),
    sa.Column('NewValue', mysql.TEXT(), nullable=True),
    sa.Column('ValueType', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['AuditLogId'], ['auditlogs.ID'], name=op.f('auditlogdetails_ibfk_1')),
    sa.PrimaryKeyConstraint('Id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('auditmetadatainfo',
    sa.Column('Id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('File_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('StartDate', mysql.DATETIME(), nullable=False),
    sa.Column('EndDate', mysql.DATETIME(), nullable=False),
    sa.Column('ModuleOrEntityName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CreatedOn', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('auditlogs',
    sa.Column('ID', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('TableName', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('Action', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('PerformedBy', mysql.CHAR(length=32), nullable=False),
    sa.Column('PerformedOn', mysql.DATETIME(), nullable=False),
    sa.Column('RecordName', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('TransactionId', mysql.CHAR(length=32), nullable=False),
    sa.Column('Comments', mysql.TEXT(), nullable=True),
    sa.Column('ModuleName', mysql.VARCHAR(length=250), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('AuditLogDetails')
    op.drop_table('AuditMetaDataInfo')
    op.drop_table('AuditLogs')
    op.drop_table('AuditFieldsMapping')
    # ### end Alembic commands ###
