
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'ba6c7bc54f35'
down_revision: Union[str, Sequence[str], None] = 'cfd418b1e5c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:

    op.add_column('departments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('departments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('departments', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('departments', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('milestones', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('milestones', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('milestones', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('milestones', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('priorities', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('priorities', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('priorities', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('priorities', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('project_groups', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('project_groups', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('project_groups', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('project_groups', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('roles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('roles', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('roles', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('skills', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('skills', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('skills', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('skills', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('statuses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('statuses', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('statuses', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('statuses', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('task_lists', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('task_lists', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('task_lists', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('task_lists', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('teams', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('teams', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('teams', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('teams', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('timelogs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('timelogs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('timelogs', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('timelogs', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('timesheets', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('timesheets', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('timesheets', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('timesheets', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('user_statuses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_statuses', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_statuses', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user_statuses', sa.Column('is_deleted', sa.Boolean(), nullable=False))

def downgrade() -> None:

    op.drop_column('user_statuses', 'is_deleted')
    op.drop_column('user_statuses', 'is_active')
    op.drop_column('user_statuses', 'updated_at')
    op.drop_column('user_statuses', 'created_at')
    op.drop_column('timesheets', 'is_deleted')
    op.drop_column('timesheets', 'is_active')
    op.drop_column('timesheets', 'updated_at')
    op.drop_column('timesheets', 'created_at')
    op.drop_column('timelogs', 'is_deleted')
    op.drop_column('timelogs', 'is_active')
    op.drop_column('timelogs', 'updated_at')
    op.drop_column('timelogs', 'created_at')
    op.drop_column('teams', 'is_deleted')
    op.drop_column('teams', 'is_active')
    op.drop_column('teams', 'updated_at')
    op.drop_column('teams', 'created_at')
    op.drop_column('task_lists', 'is_deleted')
    op.drop_column('task_lists', 'is_active')
    op.drop_column('task_lists', 'updated_at')
    op.drop_column('task_lists', 'created_at')
    op.drop_column('statuses', 'is_deleted')
    op.drop_column('statuses', 'is_active')
    op.drop_column('statuses', 'updated_at')
    op.drop_column('statuses', 'created_at')
    op.drop_column('skills', 'is_deleted')
    op.drop_column('skills', 'is_active')
    op.drop_column('skills', 'updated_at')
    op.drop_column('skills', 'created_at')
    op.drop_column('roles', 'is_deleted')
    op.drop_column('roles', 'is_active')
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    op.drop_column('project_groups', 'is_deleted')
    op.drop_column('project_groups', 'is_active')
    op.drop_column('project_groups', 'updated_at')
    op.drop_column('project_groups', 'created_at')
    op.drop_column('priorities', 'is_deleted')
    op.drop_column('priorities', 'is_active')
    op.drop_column('priorities', 'updated_at')
    op.drop_column('priorities', 'created_at')
    op.drop_column('milestones', 'is_deleted')
    op.drop_column('milestones', 'is_active')
    op.drop_column('milestones', 'updated_at')
    op.drop_column('milestones', 'created_at')
    op.drop_column('departments', 'is_deleted')
    op.drop_column('departments', 'is_active')
    op.drop_column('departments', 'updated_at')
    op.drop_column('departments', 'created_at')
