"""rename_project_budget_to_estimated_hours

Revision ID: cfd418b1e5c4
Revises: f87e61035b2d
Create Date: 2026-03-23 16:56:00.837905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cfd418b1e5c4'
down_revision: Union[str, Sequence[str], None] = 'f87e61035b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('estimated_hours', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('projects', 'budget')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('budget', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    op.drop_column('projects', 'estimated_hours')
    # ### end Alembic commands ###
