"""Email-as-Key refactor

Revision ID: ea2828384a3a
Revises: 5a96d038510a
Create Date: 2026-03-19 14:58:08.352518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ea2828384a3a'
down_revision: Union[str, Sequence[str], None] = '5a96d038510a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_document_link',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('issue_id', 'document_id')
    )
    op.add_column('documents', sa.Column('public_id', sa.String(length=50), nullable=False))
    op.add_column('documents', sa.Column('uploaded_by_email', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('documents', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.alter_column('documents', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_documents_public_id'), 'documents', ['public_id'], unique=True)
    op.drop_constraint(op.f('documents_ibfk_2'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['uploaded_by_email'], ['email'], ondelete='SET NULL')
    op.drop_column('documents', 'uploaded_by_id')
    op.add_column('issues', sa.Column('reporter_email', sa.String(length=255), nullable=True))
    op.add_column('issues', sa.Column('assignee_email', sa.String(length=255), nullable=True))
    op.add_column('issues', sa.Column('previous_status', sa.String(length=100), nullable=True))
    op.add_column('issues', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('issues', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('issues', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('issues', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('issues_ibfk_3'), 'issues', type_='foreignkey')
    op.drop_constraint(op.f('issues_ibfk_2'), 'issues', type_='foreignkey')
    op.create_foreign_key(None, 'issues', 'users', ['assignee_email'], ['email'])
    op.create_foreign_key(None, 'issues', 'users', ['reporter_email'], ['email'])
    op.drop_column('issues', 'assignee_id')
    op.drop_column('issues', 'reporter_id')
    op.add_column('projects', sa.Column('manager_email', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('created_by_email', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('previous_status', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_constraint(op.f('projects_ibfk_4'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('projects_ibfk_1'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('projects_ibfk_5'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('projects_ibfk_7'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('projects_ibfk_6'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['created_by_email'], ['email'], ondelete='SET NULL')
    op.create_foreign_key(None, 'projects', 'users', ['manager_email'], ['email'])
    op.drop_column('projects', 'team_id')
    op.drop_column('projects', 'is_template')
    op.drop_column('projects', 'created_by')
    op.drop_column('projects', 'dept_id')
    op.drop_column('projects', 'estimated_hours')
    op.drop_column('projects', 'manager_id')
    op.drop_column('projects', 'group_id')
    op.drop_column('projects', 'is_archived')
    op.add_column('tasks', sa.Column('assignee_email', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('created_by_email', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('previous_status', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('tasks_ibfk_3'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_ibfk_6'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['assignee_email'], ['email'])
    op.create_foreign_key(None, 'tasks', 'users', ['created_by_email'], ['email'], ondelete='SET NULL')
    op.drop_column('tasks', 'assignee_id')
    op.drop_column('tasks', 'created_by')
    op.add_column('users', sa.Column('manager_email', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('users_ibfk_5'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_ibfk_4'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['manager_email'], ['email'], ondelete='SET NULL')
    op.drop_column('users', 'location_id')
    op.drop_column('users', 'manager_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('manager_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('location_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_ibfk_4'), 'users', 'locations', ['location_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('users_ibfk_5'), 'users', 'users', ['manager_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'manager_email')
    op.add_column('tasks', sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('assignee_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_ibfk_6'), 'tasks', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('tasks_ibfk_3'), 'tasks', 'users', ['assignee_id'], ['id'])
    op.drop_column('tasks', 'previous_status')
    op.drop_column('tasks', 'created_by_email')
    op.drop_column('tasks', 'assignee_email')
    op.add_column('projects', sa.Column('is_archived', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('manager_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('estimated_hours', mysql.FLOAT(), nullable=True))
    op.add_column('projects', sa.Column('dept_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('is_template', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('team_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_ibfk_6'), 'projects', 'project_groups', ['group_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('projects_ibfk_7'), 'projects', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('projects_ibfk_5'), 'projects', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(op.f('projects_ibfk_1'), 'projects', 'users', ['manager_id'], ['id'])
    op.create_foreign_key(op.f('projects_ibfk_4'), 'projects', 'departments', ['dept_id'], ['id'])
    op.drop_column('projects', 'budget')
    op.drop_column('projects', 'previous_status')
    op.drop_column('projects', 'created_by_email')
    op.drop_column('projects', 'manager_email')
    op.add_column('issues', sa.Column('reporter_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('issues', sa.Column('assignee_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.create_foreign_key(op.f('issues_ibfk_2'), 'issues', 'users', ['reporter_id'], ['id'])
    op.create_foreign_key(op.f('issues_ibfk_3'), 'issues', 'users', ['assignee_id'], ['id'])
    op.drop_column('issues', 'is_deleted')
    op.drop_column('issues', 'is_active')
    op.drop_column('issues', 'updated_at')
    op.drop_column('issues', 'created_at')
    op.drop_column('issues', 'previous_status')
    op.drop_column('issues', 'assignee_email')
    op.drop_column('issues', 'reporter_email')
    op.add_column('documents', sa.Column('uploaded_by_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_ibfk_2'), 'documents', 'users', ['uploaded_by_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_documents_public_id'), table_name='documents')
    op.alter_column('documents', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('documents', 'is_deleted')
    op.drop_column('documents', 'is_active')
    op.drop_column('documents', 'uploaded_by_email')
    op.drop_column('documents', 'public_id')
    op.drop_table('issue_document_link')
    # ### end Alembic commands ###
